### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by grenzionky** [lingdoc/praatscripts#1]
i cant figure out how to use the script (tone analyzer). i followed the instructions [here](http://www.hiramring.com/posts/analyze-tone-and-plot-a-praat-script-for-exploring-analyzing-and-visualizing-or-plotting-f0-pitch-tracks), so now i have a wav and an annotated textgrid in the same folder. but i cant figure out what to do from there. 

![image](https://user-images.githubusercontent.com/13357949/71212153-c126f180-227e-11ea-9331-b1eb4ca1305b.png)
the textgrid+sound

heres what the script looks like for me, maybe i did the settings wrong. im on linux.

![image](https://user-images.githubusercontent.com/13357949/71212019-6f7e6700-227e-11ea-8d5e-a355d9fd996a.png)

running the script like this, results in an empty plot

![image](https://user-images.githubusercontent.com/13357949/71212110-a9e80400-227e-11ea-8a16-db3637cd2e31.png)

what do i need to change to get it to work? thank you

**Comment by lingdoc** [comment]
It looks like there's two things you can try:

1. In the script, it looks like the `Labeled_tier_number` is set to `2`, but you only have one tier. So try changing that to `1`.
2. The script assumes that the segments you want to measure in the corresponding tier are labeled, but I don't see any labels in the TextGrid. Segments you are trying to analyze should be labeled according to tonal category (a simple text item such as '1' or '2', 'a' or 'b' should suffice). Unlabeled TextGrid segments are ignored.

Related to #2, if you don't have multiple segments with the same label, this may be a problem further down the line as the script attempts to normalize (it's hard to normalize when there's only one token).

Does that make sense or should I post a screen shot to illustrate?

**Comment by grenzionky** [comment]
still doesnt work… im getting this error now
```
Drawing pitch curves for sound files in 'normDir$'...

Older picture file 'directory_name$''fileNameNoWav$'_'label$'_norm.png will be overwritten!

0 F0 curves were drawn and saved to 'directory_name$''fileNameNoWav$'_'label$'_norm.png.
Finished!
```

if you dont mind, heres the files im working on:
[praat-project.zip](https://github.com/lingdoc/praatscripts/files/3992110/praat-project.zip)

**Comment by lingdoc** [comment]
Hm, so looking at your files, there are a few issues in the TextGrid that seem to be throwing errors, and one in the pitch detection process. I've made some modifications in the attached files, so you can compare what I did to fix it.
[praat-project-new.zip](https://github.com/lingdoc/praatscripts/files/3992201/praat-project-new.zip)

A few comments on the changes.
1. The directory you have listed is not separated from the preceding colon ':' by a space, so it is possible the script doesn't find any files. If you are running the script from the same directory as the files, you can just remove the directory reference and it will run on the files in the same directory.
- in the attached script the directory name is blank
2. In your file names you have a '+' character. Praat uses these characters for other things, so it seems to throw an error. You should probably replace with '_' or '-'.
- in the attached files the '+' is replaced with a '_'
3. None of your intervals are labeled. The script requires labels in order to group the tones into categories for normalization.
- in the attached TextGrid the intervals are labeled (three 1s and two 2s)
4. There was a single interval (the first one) with a space (" ") which the script tries to interpret as a label. However, since there is only a single interval with this marker, it has nothing to group with.
- in the attached TextGrid the space was deleted
5. The intervals you are trying to graph are not all TBUs (Tone Bearing Units), which means they do not have continuous pitch. This is a problem since the script assumes that all the labeled intervals are TBUs and tries to get pitch information at regular intervals. When you have a lot of labeled intervals this is not such an issue, since there will usually be at least one item that has continuous pitch for each category label, but with sparse data this becomes problematic.
- in the attached TextGrid the intervals are adjusted to ensure that each interval contains a continuous pitch
6. The pitch settings are too wide/low. When I fixed the above issues and ran the script I was still getting errors. Then I noticed the pitch traces in the viewed WAV file were primarily between 150-300 Hz, so I experimented with changing the pitch analysis settings. It turns out that using a pitch analysis range of 200 (min) and 300 (max) allows the script to run without a problem. I'm not sure why this is, except that maybe it has something to do with how the sounds were produced (it sounds like computer-generated speech).
- in the attached script, the default pitch range for analysis in Hz is 200 (min) to 300 (max)

You can see some of the changes I made to the script in the following screen shot of the first window that displays when you run the script. Note that in the screen shot I also changed the number of intervals and percentage increments, but they can also remain at 50 and 20 if the pitch analysis range is 200-300 Hz.

<img width="518" alt="Screen Shot 2019-12-22 at 2 14 57 PM" src="https://user-images.githubusercontent.com/15827864/71318688-591b1a00-24cf-11ea-987f-33a596cf4870.png">

These changes give the following plot in the screen shot - also notice the default settings I changed in the plot window to make the pitches visible.

<img width="1422" alt="Screen Shot 2019-12-22 at 2 14 32 PM" src="https://user-images.githubusercontent.com/15827864/71318635-1f95df00-24ce-11ea-8709-2d91e32793d6.png">

Hopefully this helps - unfortunately much of the script depends on A) how the data is pre-processed, and B) how well Praat's built-in pitch tracer can detect the pitch of a segment. So things like the pitch range settings will need to be adjusted for your particular case. If you have hundreds of labeled segments in each category (or at least 20), this is less necessary, as the aggregate helps to mitigate detection issues.

**Comment by grenzionky** [comment]
thanks so much for taking ur time and writing such a detailed response! i really appreciate it. it works now!

i have another question: whats the green line? even when i change all labels to just "1", i still get 2 lines. i probably completely missed what the point of the 2 lines are… whats the green line?

**Comment by lingdoc** [comment]
Glad it helps!

Each line is a particular pitch trace, based on the average pitch (over time) of a set of files extracted from the WAV file based on the intervals in the text grid. If you open the folder that the files are in, you will see a subfolder. This subfolder is created for each TextGrid/WAV pair when the script is first run and contains all the extracted segments, grouped by label, for each pair.

If you are still getting the green line, it might be because the results of the first script run (the actual extracted sound files and the normalization file) are still in the respective subfolders. Try deleting the subfolder altogether and re-running the script. This should plot only the labels found in the TextGrid.

**Comment by lingdoc** [comment]
Also, the labels and corresponding colors (or line types) are printed out in the Praat console, so if it shows up there, it is clearly finding files to plot. This can be helpful if you need to know which label corresponds to which line.
